{{- define "pilox-app.postgresql-secret" -}}
{{ printf "%s-postgresql-secret" (include "pilox-app.fullname" .) }}
{{- end }}

{{- if not .Values.postgresql.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pilox-app.postgresql-secret" . }}
  labels:
    {{- include "pilox-app.labels" . | nindent 4 }}
  {{- with .Values.postgresql.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  password: {{ required "postgresql.password is required" .Values.postgresql.password | default (randAlphaNum 32) }}
{{- end }}
---
{{- if not .Values.redis.password.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pilox-app.fullname" . }}-redis-secret
  labels:
    {{- include "pilox-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.redis.password.secretKey | default "password" }}: {{ required "redis.password is required" .Values.redis.password.value | default (randAlphaNum 32) }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pilox-app.fullname" . }}-auth-secret
  labels:
    {{- include "pilox-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  AUTH_SECRET: {{ required "auth.secret is required" .Values.auth.secret | default (randAlphaNum 32) }}
{{- if .Values.auth.nextauthUrl }}
  NEXTAUTH_URL: {{ .Values.auth.nextauthUrl | quote }}
{{- end }}
