{{- if .Values.gateway.upstreamAuthSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pilox-mesh-gateway.fullname" . }}-upstream
  labels:
    {{- include "pilox-mesh-gateway.labels" . | nindent 4 }}
type: Opaque
stringData:
  auth-secret: {{ .Values.gateway.upstreamAuthSecret | quote }}
{{- end }}
