{{- if .Values.gateway.metricsAuthSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pilox-mesh-gateway.fullname" . }}-metrics
  labels:
    {{- include "pilox-mesh-gateway.labels" . | nindent 4 }}
type: Opaque
stringData:
  bearer: {{ .Values.gateway.metricsAuthSecret | quote }}
{{- end }}
