/**
 * Comprehensive open-source LLM model catalog.
 * Used by the agent creation wizard for model selection.
 *
 * Each entry includes real-world specs: parameter count, VRAM needs (Q4 quant),
 * context window, strengths, and hardware tier classification.
 */

// ── Types ────────────────────────────────────────────

export type ModelCategory =
  | "chat"
  | "code"
  | "vision"
  | "image"
  | "embedding"
  | "audio"
  | "multimodal"
  | "classifier"
  | "reasoning";

export type HardwareTier =
  | "tiny"       // 2-4 GB VRAM — phone, RPi, CPU-only laptop
  | "light"      // 4-8 GB VRAM — integrated GPU, old laptops
  | "medium"     // 12-24 GB VRAM — RTX 3090/4090, M1/M2 Pro
  | "heavy"      // 48-80 GB VRAM — A6000, dual 4090, M2 Ultra
  | "ultra";     // 80+ GB VRAM — A100/H100, multi-GPU clusters

export interface ModelEntry {
  /** Unique slug — used as the model ID when pulling */
  id: string;
  /** Human-readable display name */
  name: string;
  /** Model family grouping */
  family: string;
  /** Primary capability */
  category: ModelCategory;
  /** Additional categories */
  tags: string[];
  /** Parameter count string — "7B", "70B", "8x7B" etc. */
  params: string;
  /** Context window in tokens */
  context: number;
  /** Minimum VRAM in GB (Q4 quantization or int8 for small models) */
  vramGb: number;
  /** Recommended quantization */
  quant: string;
  /** Hardware tier classification */
  tier: HardwareTier;
  /** What it's great at — 2-4 bullet points */
  strengths: string[];
  /** Known weaknesses — 1-2 bullet points */
  weaknesses: string[];
  /** License type */
  license: string;
  /** Release date (YYYY-MM) */
  released: string;
  /** Ollama model name (if available) */
  ollamaId?: string;
  /** vLLM / HuggingFace model ID (if available) */
  vllmId?: string;
  /** HuggingFace model ID for direct link */
  huggingFaceId?: string;
  /** Whether this is an editorial recommendation */
  recommended?: boolean;
}

// ── Catalog ──────────────────────────────────────────

export const MODEL_CATALOG: ModelEntry[] = [
  // ╔══════════════════════════════════════════════════╗
  // ║  LLAMA FAMILY                                    ║
  // ╚══════════════════════════════════════════════════╝
  {
    id: "llama-3.3-70b",
    name: "Llama 3.3 70B",
    family: "Llama",
    category: "chat",
    tags: ["chat", "reasoning", "code", "multilingual"],
    params: "70B",
    context: 128_000,
    vramGb: 40,
    quant: "Q4_K_M",
    tier: "heavy",
    strengths: ["Near-GPT-4 quality on benchmarks", "128K context window", "Strong multilingual support", "Apache 2.0 — unrestricted commercial use"],
    weaknesses: ["Requires high-end GPU", "Slower inference than smaller models"],
    license: "Llama 3.3 Community",
    released: "2024-12",
    ollamaId: "llama3.3",
    recommended: true,
  },
  {
    id: "llama-3.2-3b",
    name: "Llama 3.2 3B",
    family: "Llama",
    category: "chat",
    tags: ["chat", "lightweight", "edge"],
    params: "3B",
    context: 128_000,
    vramGb: 2,
    quant: "Q4_K_M",
    tier: "tiny",
    strengths: ["Runs on CPU/phone", "128K context", "Solid for simple tasks"],
    weaknesses: ["Limited reasoning", "Weaker at code"],
    license: "Llama 3.2 Community",
    released: "2024-09",
    ollamaId: "llama3.2:3b",
  },
  {
    id: "llama-3.2-1b",
    name: "Llama 3.2 1B",
    family: "Llama",
    category: "chat",
    tags: ["chat", "lightweight", "edge", "mobile"],
    params: "1B",
    context: 128_000,
    vramGb: 1,
    quant: "Q8_0",
    tier: "tiny",
    strengths: ["Ultra-lightweight — runs on phone/RPi", "128K context", "Fast inference"],
    weaknesses: ["Very limited reasoning", "Short answers only"],
    license: "Llama 3.2 Community",
    released: "2024-09",
    ollamaId: "llama3.2:1b",
  },
  {
    id: "llama-3.1-8b",
    name: "Llama 3.1 8B Instruct",
    family: "Llama",
    category: "chat",
    tags: ["chat", "code", "instruction-following"],
    params: "8B",
    context: 128_000,
    vramGb: 5,
    quant: "Q4_K_M",
    tier: "light",
    strengths: ["Best 8B class model", "128K context", "Tool use support", "Great for RAG"],
    weaknesses: ["Not as good as 70B at complex reasoning"],
    license: "Llama 3.1 Community",
    released: "2024-07",
    ollamaId: "llama3.1:8b",
    recommended: true,
  },
  {
    id: "llama-3.1-70b",
    name: "Llama 3.1 70B Instruct",
    family: "Llama",
    category: "chat",
    tags: ["chat", "code", "reasoning", "multilingual"],
    params: "70B",
    context: 128_000,
    vramGb: 40,
    quant: "Q4_K_M",
    tier: "heavy",
    strengths: ["Top-tier open model", "128K context", "Strong code generation"],
    weaknesses: ["Heavy compute", "Needs 2x GPU or high VRAM"],
    license: "Llama 3.1 Community",
    released: "2024-07",
    ollamaId: "llama3.1:70b",
  },
  {
    id: "llama-3.1-405b",
    name: "Llama 3.1 405B Instruct",
    family: "Llama",
    category: "chat",
    tags: ["chat", "reasoning", "code", "flagship"],
    params: "405B",
    context: 128_000,
    vramGb: 230,
    quant: "FP8",
    tier: "ultra",
    strengths: ["Largest open model", "Competes with GPT-4o", "128K context"],
    weaknesses: ["Requires multi-A100 cluster", "Very expensive to run"],
    license: "Llama 3.1 Community",
    released: "2024-07",
    ollamaId: "llama3.1:405b",
  },
  {
    id: "llama-3.2-11b-vision",
    name: "Llama 3.2 11B Vision",
    family: "Llama",
    category: "vision",
    tags: ["vision", "multimodal", "image-understanding"],
    params: "11B",
    context: 128_000,
    vramGb: 8,
    quant: "Q4_K_M",
    tier: "light",
    strengths: ["Image + text understanding", "Chart/doc analysis", "128K context"],
    weaknesses: ["No image generation", "Vision quality below GPT-4V"],
    license: "Llama 3.2 Community",
    released: "2024-09",
    ollamaId: "llama3.2-vision:11b",
    recommended: true,
  },
  {
    id: "llama-3.2-90b-vision",
    name: "Llama 3.2 90B Vision",
    family: "Llama",
    category: "vision",
    tags: ["vision", "multimodal", "image-understanding"],
    params: "90B",
    context: 128_000,
    vramGb: 55,
    quant: "Q4_K_M",
    tier: "heavy",
    strengths: ["Best open-source vision model", "Image reasoning", "128K context"],
    weaknesses: ["Very heavy compute", "Requires A100 or multi-GPU"],
    license: "Llama 3.2 Community",
    released: "2024-09",
    ollamaId: "llama3.2-vision:90b",
  },
  {
    id: "codellama-34b",
    name: "Code Llama 34B Instruct",
    family: "Llama",
    category: "code",
    tags: ["code", "python", "completion", "infill"],
    params: "34B",
    context: 16_384,
    vramGb: 20,
    quant: "Q4_K_M",
    tier: "medium",
    strengths: ["Infill/completion", "Strong Python", "Code review"],
    weaknesses: ["16K context only", "Superseded by newer models"],
    license: "Llama 2 Community",
    released: "2023-08",
    ollamaId: "codellama:34b",
  },
  {
    id: "codellama-7b",
    name: "Code Llama 7B Instruct",
    family: "Llama",
    category: "code",
    tags: ["code", "python", "lightweight"],
    params: "7B",
    context: 16_384,
    vramGb: 5,
    quant: "Q4_K_M",
    tier: "light",
    strengths: ["Fast code completion", "Light weight", "Infill mode"],
    weaknesses: ["Limited context", "Older generation"],
    license: "Llama 2 Community",
    released: "2023-08",
    ollamaId: "codellama:7b",
  },

  // ╔══════════════════════════════════════════════════╗
  // ║  QWEN FAMILY                                     ║
  // ╚══════════════════════════════════════════════════╝
  {
    id: "qwen-3-8b",
    name: "Qwen 3 8B",
    family: "Qwen",
    category: "chat",
    tags: ["chat", "reasoning", "code", "multilingual", "thinking"],
    params: "8B",
    context: 128_000,
    vramGb: 5,
    quant: "Q4_K_M",
    tier: "light",
    strengths: ["Hybrid thinking mode (fast/deep)", "MCP tool use", "30+ languages", "Beats Llama 3.1 8B on most benchmarks"],
    weaknesses: ["Newer — less community tuning"],
    license: "Apache 2.0",
    released: "2025-04",
    ollamaId: "qwen3:8b",
    recommended: true,
  },
  {
    id: "qwen-3-4b",
    name: "Qwen 3 4B",
    family: "Qwen",
    category: "chat",
    tags: ["chat", "lightweight", "thinking"],
    params: "4B",
    context: 128_000,
    vramGb: 3,
    quant: "Q4_K_M",
    tier: "tiny",
    strengths: ["Hybrid thinking", "128K context", "Apache 2.0"],
    weaknesses: ["Weaker at complex reasoning"],
    license: "Apache 2.0",
    released: "2025-04",
    ollamaId: "qwen3:4b",
  },
  {
    id: "qwen-3-1.7b",
    name: "Qwen 3 1.7B",
    family: "Qwen",
    category: "chat",
    tags: ["chat", "lightweight", "edge", "thinking"],
    params: "1.7B",
    context: 128_000,
    vramGb: 1.5,
    quant: "Q4_K_M",
    tier: "tiny",
    strengths: ["Smallest model with thinking mode", "Edge deployment", "128K context"],
    weaknesses: ["Very basic reasoning"],
    license: "Apache 2.0",
    released: "2025-04",
    ollamaId: "qwen3:1.7b",
  },
  {
    id: "qwen-3-14b",
    name: "Qwen 3 14B",
    family: "Qwen",
    category: "chat",
    tags: ["chat", "reasoning", "code", "thinking"],
    params: "14B",
    context: 128_000,
    vramGb: 9,
    quant: "Q4_K_M",
    tier: "medium",
    strengths: ["Best 14B class model", "Deep thinking mode", "Agentic use"],
    weaknesses: ["Needs 12GB+ GPU"],
    license: "Apache 2.0",
    released: "2025-04",
    ollamaId: "qwen3:14b",
  },
  {
    id: "qwen-3-32b",
    name: "Qwen 3 32B",
    family: "Qwen",
    category: "chat",
    tags: ["chat", "reasoning", "code", "thinking", "agentic"],
    params: "32B",
    context: 128_000,
    vramGb: 20,
    quant: "Q4_K_M",
    tier: "medium",
    strengths: ["Beats GPT-4o on many benchmarks", "Hybrid thinking", "Excellent agentic behavior"],
    weaknesses: ["Needs 24GB GPU"],
    license: "Apache 2.0",
    released: "2025-04",
    ollamaId: "qwen3:32b",
    recommended: true,
  },
  {
    id: "qwen-3-235b-a22b",
    name: "Qwen 3 235B (MoE, A22B)",
    family: "Qwen",
    category: "chat",
    tags: ["chat", "reasoning", "code", "thinking", "flagship"],
    params: "235B (22B active)",
    context: 128_000,
    vramGb: 60,
    quant: "Q4_K_M",
    tier: "heavy",
    strengths: ["Best open model period", "MoE — fast despite size", "Deep thinking", "Competes with Claude 3.5"],
    weaknesses: ["Requires 80GB+ VRAM or multi-GPU"],
    license: "Apache 2.0",
    released: "2025-04",
    ollamaId: "qwen3:235b-a22b",
  },
  {
    id: "qwen-2.5-72b",
    name: "Qwen 2.5 72B Instruct",
    family: "Qwen",
    category: "chat",
    tags: ["chat", "reasoning", "code", "multilingual"],
    params: "72B",
    context: 131_072,
    vramGb: 42,
    quant: "Q4_K_M",
    tier: "heavy",
    strengths: ["128K context", "Strong math", "30+ languages"],
    weaknesses: ["Superseded by Qwen 3"],
    license: "Apache 2.0",
    released: "2024-09",
    ollamaId: "qwen2.5:72b",
  },
  {
    id: "qwen-2.5-7b",
    name: "Qwen 2.5 7B Instruct",
    family: "Qwen",
    category: "chat",
    tags: ["chat", "code", "lightweight"],
    params: "7B",
    context: 131_072,
    vramGb: 5,
    quant: "Q4_K_M",
    tier: "light",
    strengths: ["Great 7B model", "128K context", "Apache 2.0"],
    weaknesses: ["Superseded by Qwen 3 8B"],
    license: "Apache 2.0",
    released: "2024-09",
    ollamaId: "qwen2.5:7b",
  },
  {
    id: "qwen-2.5-coder-32b",
    name: "Qwen 2.5 Coder 32B",
    family: "Qwen",
    category: "code",
    tags: ["code", "completion", "generation", "refactoring"],
    params: "32B",
    context: 131_072,
    vramGb: 20,
    quant: "Q4_K_M",
    tier: "medium",
    strengths: ["Best open-source code model", "128K context", "92+ languages", "Beats GPT-4o on code"],
    weaknesses: ["Focused on code — weaker at general chat"],
    license: "Apache 2.0",
    released: "2024-11",
    ollamaId: "qwen2.5-coder:32b",
    recommended: true,
  },
  {
    id: "qwen-2.5-coder-7b",
    name: "Qwen 2.5 Coder 7B",
    family: "Qwen",
    category: "code",
    tags: ["code", "completion", "lightweight"],
    params: "7B",
    context: 131_072,
    vramGb: 5,
    quant: "Q4_K_M",
    tier: "light",
    strengths: ["Fast code completion", "128K context", "Great for IDE copilot"],
    weaknesses: ["Less capable than 32B variant"],
    license: "Apache 2.0",
    released: "2024-11",
    ollamaId: "qwen2.5-coder:7b",
  },
  {
    id: "qwen-2.5-coder-1.5b",
    name: "Qwen 2.5 Coder 1.5B",
    family: "Qwen",
    category: "code",
    tags: ["code", "completion", "edge", "lightweight"],
    params: "1.5B",
    context: 131_072,
    vramGb: 1.5,
    quant: "Q8_0",
    tier: "tiny",
    strengths: ["Ultra-fast autocomplete", "Edge deployment", "128K context"],
    weaknesses: ["Limited generation quality"],
    license: "Apache 2.0",
    released: "2024-11",
    ollamaId: "qwen2.5-coder:1.5b",
  },
  {
    id: "qwen-2-vl-72b",
    name: "Qwen 2 VL 72B",
    family: "Qwen",
    category: "vision",
    tags: ["vision", "multimodal", "video", "document"],
    params: "72B",
    context: 32_768,
    vramGb: 42,
    quant: "Q4_K_M",
    tier: "heavy",
    strengths: ["Image + video understanding", "Document OCR", "Chart analysis"],
    weaknesses: ["Very heavy compute"],
    license: "Apache 2.0",
    released: "2024-10",
    ollamaId: "qwen2-vl:72b",
  },
  {
    id: "qwen-2-vl-7b",
    name: "Qwen 2 VL 7B",
    family: "Qwen",
    category: "vision",
    tags: ["vision", "multimodal", "lightweight"],
    params: "7B",
    context: 32_768,
    vramGb: 6,
    quant: "Q4_K_M",
    tier: "light",
    strengths: ["Vision + text", "Document understanding", "Lightweight"],
    weaknesses: ["32K context only"],
    license: "Apache 2.0",
    released: "2024-10",
    ollamaId: "qwen2-vl:7b",
  },

  // ╔══════════════════════════════════════════════════╗
  // ║  MISTRAL FAMILY                                  ║
  // ╚══════════════════════════════════════════════════╝
  {
    id: "mistral-7b",
    name: "Mistral 7B Instruct v0.3",
    family: "Mistral",
    category: "chat",
    tags: ["chat", "instruction-following", "lightweight"],
    params: "7B",
    context: 32_768,
    vramGb: 5,
    quant: "Q4_K_M",
    tier: "light",
    strengths: ["Pioneer efficient 7B model", "Sliding window attention", "Fast inference"],
    weaknesses: ["Superseded by newer models", "32K context"],
    license: "Apache 2.0",
    released: "2023-12",
    ollamaId: "mistral:7b",
  },
  {
    id: "mistral-nemo-12b",
    name: "Mistral Nemo 12B",
    family: "Mistral",
    category: "chat",
    tags: ["chat", "reasoning", "multilingual"],
    params: "12B",
    context: 128_000,
    vramGb: 8,
    quant: "Q4_K_M",
    tier: "light",
    strengths: ["128K context", "Strong multilingual", "Built with NVIDIA", "Tekken tokenizer"],
    weaknesses: ["Slightly heavy for 12B class"],
    license: "Apache 2.0",
    released: "2024-07",
    ollamaId: "mistral-nemo",
    recommended: true,
  },
  {
    id: "mixtral-8x7b",
    name: "Mixtral 8x7B Instruct",
    family: "Mistral",
    category: "chat",
    tags: ["chat", "MoE", "code", "multilingual"],
    params: "8x7B (12.9B active)",
    context: 32_768,
    vramGb: 26,
    quant: "Q4_K_M",
    tier: "medium",
    strengths: ["MoE — fast for its quality", "Strong multilingual", "Good code generation"],
    weaknesses: ["Large disk footprint", "32K context"],
    license: "Apache 2.0",
    released: "2024-01",
    ollamaId: "mixtral:8x7b",
  },
  {
    id: "mixtral-8x22b",
    name: "Mixtral 8x22B Instruct",
    family: "Mistral",
    category: "chat",
    tags: ["chat", "MoE", "reasoning", "code"],
    params: "8x22B (39B active)",
    context: 65_536,
    vramGb: 80,
    quant: "Q4_K_M",
    tier: "ultra",
    strengths: ["Excellent MoE model", "64K context", "Strong math + code"],
    weaknesses: ["Requires multi-GPU or A100", "Huge disk footprint"],
    license: "Apache 2.0",
    released: "2024-04",
    ollamaId: "mixtral:8x22b",
  },
  {
    id: "mistral-small-24b",
    name: "Mistral Small 3.1 24B",
    family: "Mistral",
    category: "chat",
    tags: ["chat", "reasoning", "vision", "multilingual"],
    params: "24B",
    context: 128_000,
    vramGb: 15,
    quant: "Q4_K_M",
    tier: "medium",
    strengths: ["Vision-capable", "128K context", "Strong function calling", "Apache 2.0"],
    weaknesses: ["Needs 16GB+ GPU"],
    license: "Apache 2.0",
    released: "2025-03",
    ollamaId: "mistral-small:24b",
    recommended: true,
  },
  {
    id: "codestral-22b",
    name: "Codestral 22B",
    family: "Mistral",
    category: "code",
    tags: ["code", "completion", "infill", "generation"],
    params: "22B",
    context: 32_768,
    vramGb: 14,
    quant: "Q4_K_M",
    tier: "medium",
    strengths: ["80+ programming languages", "FIM (fill-in-middle)", "Fast code generation"],
    weaknesses: ["Non-production license for some uses", "32K context"],
    license: "MNPL",
    released: "2024-05",
    ollamaId: "codestral:22b",
  },
  {
    id: "codestral-mamba-7b",
    name: "Codestral Mamba 7B",
    family: "Mistral",
    category: "code",
    tags: ["code", "mamba", "linear-attention"],
    params: "7B",
    context: 256_000,
    vramGb: 5,
    quant: "Q4_K_M",
    tier: "light",
    strengths: ["256K context — Mamba architecture", "Linear-time inference", "Great for long files"],
    weaknesses: ["Lower peak quality vs transformer models"],
    license: "Apache 2.0",
    released: "2024-07",
    ollamaId: "codestral-mamba",
  },
  {
    id: "pixtral-12b",
    name: "Pixtral 12B",
    family: "Mistral",
    category: "vision",
    tags: ["vision", "multimodal", "document"],
    params: "12B",
    context: 128_000,
    vramGb: 8,
    quant: "Q4_K_M",
    tier: "light",
    strengths: ["Native multimodal", "Variable-res images", "128K context"],
    weaknesses: ["Newer — smaller community"],
    license: "Apache 2.0",
    released: "2024-09",
    ollamaId: "pixtral",
  },

  // ╔══════════════════════════════════════════════════╗
  // ║  DEEPSEEK FAMILY                                 ║
  // ╚══════════════════════════════════════════════════╝
  {
    id: "deepseek-r1-distill-qwen-32b",
    name: "DeepSeek R1 Distill Qwen 32B",
    family: "DeepSeek",
    category: "reasoning",
    tags: ["reasoning", "math", "code", "thinking"],
    params: "32B",
    context: 131_072,
    vramGb: 20,
    quant: "Q4_K_M",
    tier: "medium",
    strengths: ["R1-level reasoning in 32B", "Chain-of-thought built in", "Excellent math", "128K context"],
    weaknesses: ["Slower due to thinking overhead"],
    license: "MIT",
    released: "2025-01",
    ollamaId: "deepseek-r1:32b",
    recommended: true,
  },
  {
    id: "deepseek-r1-distill-qwen-14b",
    name: "DeepSeek R1 Distill Qwen 14B",
    family: "DeepSeek",
    category: "reasoning",
    tags: ["reasoning", "math", "thinking"],
    params: "14B",
    context: 131_072,
    vramGb: 9,
    quant: "Q4_K_M",
    tier: "medium",
    strengths: ["Reasoning in small form factor", "128K context", "MIT license"],
    weaknesses: ["Lower quality than 32B distill"],
    license: "MIT",
    released: "2025-01",
    ollamaId: "deepseek-r1:14b",
  },
  {
    id: "deepseek-r1-distill-qwen-7b",
    name: "DeepSeek R1 Distill Qwen 7B",
    family: "DeepSeek",
    category: "reasoning",
    tags: ["reasoning", "math", "lightweight", "thinking"],
    params: "7B",
    context: 131_072,
    vramGb: 5,
    quant: "Q4_K_M",
    tier: "light",
    strengths: ["Chain-of-thought at 7B", "128K context", "MIT license"],
    weaknesses: ["Reasoning quality limited by size"],
    license: "MIT",
    released: "2025-01",
    ollamaId: "deepseek-r1:7b",
  },
  {
    id: "deepseek-r1-distill-llama-8b",
    name: "DeepSeek R1 Distill Llama 8B",
    family: "DeepSeek",
    category: "reasoning",
    tags: ["reasoning", "math", "thinking"],
    params: "8B",
    context: 128_000,
    vramGb: 5,
    quant: "Q4_K_M",
    tier: "light",
    strengths: ["Llama-based distill", "128K context", "MIT license"],
    weaknesses: ["Slightly below Qwen distill quality"],
    license: "MIT",
    released: "2025-01",
    ollamaId: "deepseek-r1:8b-llama",
  },
  {
    id: "deepseek-r1-distill-llama-70b",
    name: "DeepSeek R1 Distill Llama 70B",
    family: "DeepSeek",
    category: "reasoning",
    tags: ["reasoning", "math", "code", "thinking"],
    params: "70B",
    context: 128_000,
    vramGb: 40,
    quant: "Q4_K_M",
    tier: "heavy",
    strengths: ["Strongest distill variant", "Matches o1-mini on math", "128K context"],
    weaknesses: ["Heavy compute"],
    license: "MIT",
    released: "2025-01",
    ollamaId: "deepseek-r1:70b",
  },
  {
    id: "deepseek-r1-671b",
    name: "DeepSeek R1 671B",
    family: "DeepSeek",
    category: "reasoning",
    tags: ["reasoning", "math", "code", "thinking", "flagship"],
    params: "671B (37B active MoE)",
    context: 128_000,
    vramGb: 160,
    quant: "FP8",
    tier: "ultra",
    strengths: ["Matches o1 on reasoning benchmarks", "MoE — efficient for size", "MIT license"],
    weaknesses: ["Requires multi-A100 cluster"],
    license: "MIT",
    released: "2025-01",
    ollamaId: "deepseek-r1:671b",
  },
  {
    id: "deepseek-v3-671b",
    name: "DeepSeek V3 671B",
    family: "DeepSeek",
    category: "chat",
    tags: ["chat", "code", "reasoning", "flagship"],
    params: "671B (37B active MoE)",
    context: 128_000,
    vramGb: 160,
    quant: "FP8",
    tier: "ultra",
    strengths: ["Best general open model (pre-R1)", "MoE architecture", "Very strong at code"],
    weaknesses: ["Requires massive hardware"],
    license: "MIT",
    released: "2024-12",
    ollamaId: "deepseek-v3",
  },
  {
    id: "deepseek-coder-v2-16b",
    name: "DeepSeek Coder V2 16B",
    family: "DeepSeek",
    category: "code",
    tags: ["code", "completion", "generation"],
    params: "16B",
    context: 128_000,
    vramGb: 10,
    quant: "Q4_K_M",
    tier: "medium",
    strengths: ["128K context for code", "Strong completion", "MIT license"],
    weaknesses: ["Superseded by Qwen 2.5 Coder"],
    license: "MIT",
    released: "2024-06",
    ollamaId: "deepseek-coder-v2:16b",
  },

  // ╔══════════════════════════════════════════════════╗
  // ║  GOOGLE GEMMA FAMILY                             ║
  // ╚══════════════════════════════════════════════════╝
  {
    id: "gemma-3-27b",
    name: "Gemma 3 27B",
    family: "Gemma",
    category: "chat",
    tags: ["chat", "reasoning", "vision", "multilingual"],
    params: "27B",
    context: 128_000,
    vramGb: 17,
    quant: "Q4_K_M",
    tier: "medium",
    strengths: ["Vision + text", "128K context", "Strong benchmarks for size", "Google-quality training data"],
    weaknesses: ["Gemma license — some restrictions"],
    license: "Gemma",
    released: "2025-03",
    ollamaId: "gemma3:27b",
    recommended: true,
  },
  {
    id: "gemma-3-12b",
    name: "Gemma 3 12B",
    family: "Gemma",
    category: "chat",
    tags: ["chat", "vision", "multilingual"],
    params: "12B",
    context: 128_000,
    vramGb: 8,
    quant: "Q4_K_M",
    tier: "light",
    strengths: ["Vision capable", "128K context", "Great for its size"],
    weaknesses: ["Gemma license restrictions"],
    license: "Gemma",
    released: "2025-03",
    ollamaId: "gemma3:12b",
  },
  {
    id: "gemma-3-4b",
    name: "Gemma 3 4B",
    family: "Gemma",
    category: "chat",
    tags: ["chat", "vision", "lightweight"],
    params: "4B",
    context: 128_000,
    vramGb: 3,
    quant: "Q4_K_M",
    tier: "tiny",
    strengths: ["Vision in a 4B model", "128K context", "Edge-ready"],
    weaknesses: ["Limited reasoning"],
    license: "Gemma",
    released: "2025-03",
    ollamaId: "gemma3:4b",
  },
  {
    id: "gemma-3-1b",
    name: "Gemma 3 1B",
    family: "Gemma",
    category: "chat",
    tags: ["chat", "lightweight", "edge", "mobile"],
    params: "1B",
    context: 32_768,
    vramGb: 1,
    quant: "Q8_0",
    tier: "tiny",
    strengths: ["Ultra-small", "Runs on phone", "Fast inference"],
    weaknesses: ["Very limited", "32K context only"],
    license: "Gemma",
    released: "2025-03",
    ollamaId: "gemma3:1b",
  },
  {
    id: "gemma-2-9b",
    name: "Gemma 2 9B Instruct",
    family: "Gemma",
    category: "chat",
    tags: ["chat", "instruction-following"],
    params: "9B",
    context: 8_192,
    vramGb: 6,
    quant: "Q4_K_M",
    tier: "light",
    strengths: ["Solid 9B chat model", "Google architecture"],
    weaknesses: ["8K context only", "Superseded by Gemma 3"],
    license: "Gemma",
    released: "2024-06",
    ollamaId: "gemma2:9b",
  },
  {
    id: "gemma-2-27b",
    name: "Gemma 2 27B Instruct",
    family: "Gemma",
    category: "chat",
    tags: ["chat", "reasoning"],
    params: "27B",
    context: 8_192,
    vramGb: 17,
    quant: "Q4_K_M",
    tier: "medium",
    strengths: ["Strong for 27B class", "Good instruction following"],
    weaknesses: ["8K context only", "Superseded by Gemma 3"],
    license: "Gemma",
    released: "2024-06",
    ollamaId: "gemma2:27b",
  },
  {
    id: "codegemma-7b",
    name: "CodeGemma 7B",
    family: "Gemma",
    category: "code",
    tags: ["code", "completion", "infill"],
    params: "7B",
    context: 8_192,
    vramGb: 5,
    quant: "Q4_K_M",
    tier: "light",
    strengths: ["Fill-in-middle support", "Good for autocomplete"],
    weaknesses: ["8K context", "Older generation"],
    license: "Gemma",
    released: "2024-04",
    ollamaId: "codegemma:7b",
  },

  // ╔══════════════════════════════════════════════════╗
  // ║  MICROSOFT PHI FAMILY                            ║
  // ╚══════════════════════════════════════════════════╝
  {
    id: "phi-4-14b",
    name: "Phi-4 14B",
    family: "Phi",
    category: "chat",
    tags: ["chat", "reasoning", "math", "code"],
    params: "14B",
    context: 16_384,
    vramGb: 9,
    quant: "Q4_K_M",
    tier: "medium",
    strengths: ["Exceptional reasoning for size", "Strong math/STEM", "MIT license"],
    weaknesses: ["16K context", "Weaker at creative writing"],
    license: "MIT",
    released: "2024-12",
    ollamaId: "phi4:14b",
    recommended: true,
  },
  {
    id: "phi-4-mini-3.8b",
    name: "Phi-4 Mini 3.8B",
    family: "Phi",
    category: "chat",
    tags: ["chat", "reasoning", "lightweight", "edge"],
    params: "3.8B",
    context: 128_000,
    vramGb: 3,
    quant: "Q4_K_M",
    tier: "tiny",
    strengths: ["128K context in 3.8B!", "Beats Llama 3.2 3B", "MIT license", "MoE-like sparse routing"],
    weaknesses: ["Not great at long-form generation"],
    license: "MIT",
    released: "2025-02",
    ollamaId: "phi4-mini",
  },
  {
    id: "phi-3.5-mini-3.8b",
    name: "Phi-3.5 Mini 3.8B",
    family: "Phi",
    category: "chat",
    tags: ["chat", "lightweight", "reasoning"],
    params: "3.8B",
    context: 128_000,
    vramGb: 3,
    quant: "Q4_K_M",
    tier: "tiny",
    strengths: ["128K context", "Strong reasoning for size", "MIT license"],
    weaknesses: ["Superseded by Phi-4 Mini"],
    license: "MIT",
    released: "2024-08",
    ollamaId: "phi3.5:3.8b",
  },
  {
    id: "phi-3.5-vision",
    name: "Phi-3.5 Vision 4.2B",
    family: "Phi",
    category: "vision",
    tags: ["vision", "multimodal", "lightweight", "document"],
    params: "4.2B",
    context: 128_000,
    vramGb: 4,
    quant: "Q4_K_M",
    tier: "light",
    strengths: ["Vision at 4B scale", "Multi-frame/video input", "Document OCR", "128K context"],
    weaknesses: ["Lower vision quality vs larger models"],
    license: "MIT",
    released: "2024-08",
    ollamaId: "phi3.5-vision",
  },
  {
    id: "phi-3-medium-14b",
    name: "Phi-3 Medium 14B",
    family: "Phi",
    category: "chat",
    tags: ["chat", "reasoning", "math"],
    params: "14B",
    context: 128_000,
    vramGb: 9,
    quant: "Q4_K_M",
    tier: "medium",
    strengths: ["128K context", "Strong at STEM"],
    weaknesses: ["Superseded by Phi-4"],
    license: "MIT",
    released: "2024-05",
    ollamaId: "phi3:14b",
  },

  // ╔══════════════════════════════════════════════════╗
  // ║  COHERE COMMAND FAMILY                           ║
  // ╚══════════════════════════════════════════════════╝
  {
    id: "command-r-35b",
    name: "Command R 35B",
    family: "Command",
    category: "chat",
    tags: ["chat", "RAG", "tool-use", "multilingual"],
    params: "35B",
    context: 128_000,
    vramGb: 21,
    quant: "Q4_K_M",
    tier: "medium",
    strengths: ["Built for RAG", "Grounded generation", "128K context", "10+ languages"],
    weaknesses: ["CC-BY-NC license (non-commercial)"],
    license: "CC-BY-NC",
    released: "2024-03",
    ollamaId: "command-r",
  },
  {
    id: "command-r-plus-104b",
    name: "Command R+ 104B",
    family: "Command",
    category: "chat",
    tags: ["chat", "RAG", "reasoning", "multilingual"],
    params: "104B",
    context: 128_000,
    vramGb: 60,
    quant: "Q4_K_M",
    tier: "heavy",
    strengths: ["Best RAG model", "Multi-step tool use", "128K context"],
    weaknesses: ["CC-BY-NC license", "Very heavy"],
    license: "CC-BY-NC",
    released: "2024-04",
    ollamaId: "command-r-plus",
  },
  {
    id: "aya-expanse-32b",
    name: "Aya Expanse 32B",
    family: "Command",
    category: "chat",
    tags: ["chat", "multilingual", "23-languages"],
    params: "32B",
    context: 128_000,
    vramGb: 20,
    quant: "Q4_K_M",
    tier: "medium",
    strengths: ["23 languages", "Best multilingual open model", "128K context"],
    weaknesses: ["CC-BY-NC license"],
    license: "CC-BY-NC",
    released: "2024-11",
    ollamaId: "aya-expanse:32b",
  },
  {
    id: "aya-expanse-8b",
    name: "Aya Expanse 8B",
    family: "Command",
    category: "chat",
    tags: ["chat", "multilingual", "lightweight"],
    params: "8B",
    context: 8_192,
    vramGb: 5,
    quant: "Q4_K_M",
    tier: "light",
    strengths: ["23 languages in 8B", "Lightweight multilingual"],
    weaknesses: ["8K context only"],
    license: "CC-BY-NC",
    released: "2024-11",
    ollamaId: "aya-expanse:8b",
  },

  // ╔══════════════════════════════════════════════════╗
  // ║  STARCODER / BIGCODE                             ║
  // ╚══════════════════════════════════════════════════╝
  {
    id: "starcoder2-15b",
    name: "StarCoder2 15B",
    family: "StarCoder",
    category: "code",
    tags: ["code", "completion", "generation", "600-languages"],
    params: "15B",
    context: 16_384,
    vramGb: 10,
    quant: "Q4_K_M",
    tier: "medium",
    strengths: ["600+ programming languages", "BigCode community", "Good code completion"],
    weaknesses: ["16K context", "Superseded by Qwen Coder"],
    license: "BigCode OpenRAIL-M",
    released: "2024-02",
    ollamaId: "starcoder2:15b",
  },
  {
    id: "starcoder2-7b",
    name: "StarCoder2 7B",
    family: "StarCoder",
    category: "code",
    tags: ["code", "completion", "lightweight"],
    params: "7B",
    context: 16_384,
    vramGb: 5,
    quant: "Q4_K_M",
    tier: "light",
    strengths: ["600+ languages", "Fast completion"],
    weaknesses: ["16K context", "Lower quality than larger variants"],
    license: "BigCode OpenRAIL-M",
    released: "2024-02",
    ollamaId: "starcoder2:7b",
  },
  {
    id: "starcoder2-3b",
    name: "StarCoder2 3B",
    family: "StarCoder",
    category: "code",
    tags: ["code", "completion", "edge"],
    params: "3B",
    context: 16_384,
    vramGb: 2,
    quant: "Q4_K_M",
    tier: "tiny",
    strengths: ["Edge code completion", "600+ languages"],
    weaknesses: ["Limited generation quality"],
    license: "BigCode OpenRAIL-M",
    released: "2024-02",
    ollamaId: "starcoder2:3b",
  },

  // ╔══════════════════════════════════════════════════╗
  // ║  YI FAMILY                                       ║
  // ╚══════════════════════════════════════════════════╝
  {
    id: "yi-1.5-34b",
    name: "Yi-1.5 34B Chat",
    family: "Yi",
    category: "chat",
    tags: ["chat", "reasoning", "bilingual"],
    params: "34B",
    context: 32_768,
    vramGb: 21,
    quant: "Q4_K_M",
    tier: "medium",
    strengths: ["Strong bilingual (EN/ZH)", "Good reasoning", "Apache 2.0"],
    weaknesses: ["Superseded by newer models"],
    license: "Apache 2.0",
    released: "2024-05",
    ollamaId: "yi:34b",
  },
  {
    id: "yi-1.5-9b",
    name: "Yi-1.5 9B Chat",
    family: "Yi",
    category: "chat",
    tags: ["chat", "bilingual", "lightweight"],
    params: "9B",
    context: 32_768,
    vramGb: 6,
    quant: "Q4_K_M",
    tier: "light",
    strengths: ["Good bilingual chat", "Apache 2.0"],
    weaknesses: ["32K context"],
    license: "Apache 2.0",
    released: "2024-05",
    ollamaId: "yi:9b",
  },

  // ╔══════════════════════════════════════════════════╗
  // ║  INTERNLM FAMILY                                 ║
  // ╚══════════════════════════════════════════════════╝
  {
    id: "internlm2.5-20b",
    name: "InternLM 2.5 20B",
    family: "InternLM",
    category: "chat",
    tags: ["chat", "reasoning", "math", "tool-use"],
    params: "20B",
    context: 32_768,
    vramGb: 13,
    quant: "Q4_K_M",
    tier: "medium",
    strengths: ["Strong math reasoning", "Tool use built-in", "Good Chinese support"],
    weaknesses: ["Less English-focused"],
    license: "Apache 2.0",
    released: "2024-07",
    ollamaId: "internlm2:20b",
  },
  {
    id: "internlm2.5-7b",
    name: "InternLM 2.5 7B",
    family: "InternLM",
    category: "chat",
    tags: ["chat", "reasoning", "lightweight"],
    params: "7B",
    context: 32_768,
    vramGb: 5,
    quant: "Q4_K_M",
    tier: "light",
    strengths: ["Good math", "Tool use", "Apache 2.0"],
    weaknesses: ["32K context"],
    license: "Apache 2.0",
    released: "2024-07",
    ollamaId: "internlm2:7b",
  },

  // ╔══════════════════════════════════════════════════╗
  // ║  OTHER CHAT MODELS                               ║
  // ╚══════════════════════════════════════════════════╝
  {
    id: "solar-10.7b",
    name: "Solar 10.7B Instruct",
    family: "Solar",
    category: "chat",
    tags: ["chat", "instruction-following"],
    params: "10.7B",
    context: 4_096,
    vramGb: 7,
    quant: "Q4_K_M",
    tier: "light",
    strengths: ["Depth-upscaled architecture", "Good instruction following"],
    weaknesses: ["4K context only", "Older model"],
    license: "Apache 2.0",
    released: "2023-12",
    ollamaId: "solar:10.7b",
  },
  {
    id: "neural-chat-7b",
    name: "Neural Chat 7B (Intel)",
    family: "Intel",
    category: "chat",
    tags: ["chat", "instruction-following", "intel"],
    params: "7B",
    context: 8_192,
    vramGb: 5,
    quant: "Q4_K_M",
    tier: "light",
    strengths: ["Intel-optimized", "Good general chat"],
    weaknesses: ["8K context", "Older model"],
    license: "Apache 2.0",
    released: "2023-11",
    ollamaId: "neural-chat:7b",
  },
  {
    id: "openchat-3.5-7b",
    name: "OpenChat 3.5 7B",
    family: "OpenChat",
    category: "chat",
    tags: ["chat", "instruction-following"],
    params: "7B",
    context: 8_192,
    vramGb: 5,
    quant: "Q4_K_M",
    tier: "light",
    strengths: ["C-RLFT training method", "Good chat quality for 7B"],
    weaknesses: ["8K context", "Superseded"],
    license: "Apache 2.0",
    released: "2023-11",
    ollamaId: "openchat:7b",
  },
  {
    id: "zephyr-7b",
    name: "Zephyr 7B Beta",
    family: "Zephyr",
    category: "chat",
    tags: ["chat", "instruction-following", "DPO"],
    params: "7B",
    context: 32_768,
    vramGb: 5,
    quant: "Q4_K_M",
    tier: "light",
    strengths: ["DPO-trained for helpfulness", "Good alignment"],
    weaknesses: ["Older generation"],
    license: "MIT",
    released: "2023-10",
    ollamaId: "zephyr:7b",
  },
  {
    id: "vicuna-33b",
    name: "Vicuna 33B v1.3",
    family: "Vicuna",
    category: "chat",
    tags: ["chat", "instruction-following"],
    params: "33B",
    context: 2_048,
    vramGb: 20,
    quant: "Q4_K_M",
    tier: "medium",
    strengths: ["Pioneer open-source chatbot", "Good conversation quality"],
    weaknesses: ["2K context", "Very old", "Non-commercial"],
    license: "Non-commercial",
    released: "2023-06",
    ollamaId: "vicuna:33b",
  },
  {
    id: "falcon-40b",
    name: "Falcon 40B Instruct",
    family: "Falcon",
    category: "chat",
    tags: ["chat", "instruction-following"],
    params: "40B",
    context: 2_048,
    vramGb: 24,
    quant: "Q4_K_M",
    tier: "medium",
    strengths: ["TII training on RefinedWeb", "Apache 2.0"],
    weaknesses: ["2K context", "Superseded by modern models"],
    license: "Apache 2.0",
    released: "2023-06",
    ollamaId: "falcon:40b",
  },
  {
    id: "falcon-180b",
    name: "Falcon 180B Chat",
    family: "Falcon",
    category: "chat",
    tags: ["chat", "reasoning", "flagship"],
    params: "180B",
    context: 2_048,
    vramGb: 100,
    quant: "Q4_K_M",
    tier: "ultra",
    strengths: ["Massive scale", "Strong general reasoning"],
    weaknesses: ["2K context", "Extremely heavy", "Superseded"],
    license: "Falcon-180B TII License",
    released: "2023-09",
    ollamaId: "falcon:180b",
  },
  {
    id: "stablelm-zephyr-3b",
    name: "StableLM Zephyr 3B",
    family: "StableLM",
    category: "chat",
    tags: ["chat", "lightweight", "edge"],
    params: "3B",
    context: 4_096,
    vramGb: 2,
    quant: "Q4_K_M",
    tier: "tiny",
    strengths: ["Very lightweight", "Good for edge", "Fast inference"],
    weaknesses: ["4K context", "Limited capability"],
    license: "StabilityAI Non-Commercial",
    released: "2023-12",
    ollamaId: "stablelm-zephyr:3b",
  },
  {
    id: "olmo-2-13b",
    name: "OLMo 2 13B Instruct",
    family: "OLMo",
    category: "chat",
    tags: ["chat", "open-science", "reasoning"],
    params: "13B",
    context: 4_096,
    vramGb: 8,
    quant: "Q4_K_M",
    tier: "light",
    strengths: ["Fully open (data + training code + weights)", "Apache 2.0", "AI2 research quality"],
    weaknesses: ["4K context", "Smaller community"],
    license: "Apache 2.0",
    released: "2024-11",
    ollamaId: "olmo2:13b",
  },
  {
    id: "olmo-2-7b",
    name: "OLMo 2 7B Instruct",
    family: "OLMo",
    category: "chat",
    tags: ["chat", "open-science", "lightweight"],
    params: "7B",
    context: 4_096,
    vramGb: 5,
    quant: "Q4_K_M",
    tier: "light",
    strengths: ["Fully open", "Apache 2.0"],
    weaknesses: ["4K context"],
    license: "Apache 2.0",
    released: "2024-11",
    ollamaId: "olmo2:7b",
  },
  {
    id: "granite-3.1-8b",
    name: "Granite 3.1 8B Instruct",
    family: "Granite",
    category: "chat",
    tags: ["chat", "enterprise", "tool-use", "RAG"],
    params: "8B",
    context: 128_000,
    vramGb: 5,
    quant: "Q4_K_M",
    tier: "light",
    strengths: ["IBM enterprise model", "128K context", "Built-in tool use", "Apache 2.0"],
    weaknesses: ["Less community adoption"],
    license: "Apache 2.0",
    released: "2024-12",
    ollamaId: "granite3.1-dense:8b",
  },
  {
    id: "granite-3.1-2b",
    name: "Granite 3.1 2B Instruct",
    family: "Granite",
    category: "chat",
    tags: ["chat", "enterprise", "lightweight", "edge"],
    params: "2B",
    context: 128_000,
    vramGb: 1.5,
    quant: "Q4_K_M",
    tier: "tiny",
    strengths: ["128K context in 2B!", "Enterprise-grade", "Apache 2.0"],
    weaknesses: ["Limited reasoning"],
    license: "Apache 2.0",
    released: "2024-12",
    ollamaId: "granite3.1-dense:2b",
  },
  {
    id: "exaone-3.5-32b",
    name: "EXAONE 3.5 32B",
    family: "EXAONE",
    category: "chat",
    tags: ["chat", "reasoning", "bilingual", "korean"],
    params: "32B",
    context: 32_768,
    vramGb: 20,
    quant: "Q4_K_M",
    tier: "medium",
    strengths: ["LG AI Research", "Strong bilingual (EN/KO)", "Good reasoning"],
    weaknesses: ["Smaller community"],
    license: "EXAONE AI Model License",
    released: "2024-12",
    ollamaId: "exaone3.5:32b",
  },
  {
    id: "smollm2-1.7b",
    name: "SmolLM2 1.7B Instruct",
    family: "SmolLM",
    category: "chat",
    tags: ["chat", "edge", "mobile", "lightweight"],
    params: "1.7B",
    context: 8_192,
    vramGb: 1.5,
    quant: "Q8_0",
    tier: "tiny",
    strengths: ["HuggingFace edge model", "Apache 2.0", "On-device ready"],
    weaknesses: ["8K context", "Very limited"],
    license: "Apache 2.0",
    released: "2024-11",
    ollamaId: "smollm2:1.7b",
  },
  {
    id: "smollm2-360m",
    name: "SmolLM2 360M Instruct",
    family: "SmolLM",
    category: "chat",
    tags: ["chat", "edge", "mobile", "ultra-light"],
    params: "360M",
    context: 8_192,
    vramGb: 0.5,
    quant: "FP16",
    tier: "tiny",
    strengths: ["Ultra-tiny — runs on any device", "Apache 2.0"],
    weaknesses: ["Very basic capabilities"],
    license: "Apache 2.0",
    released: "2024-11",
    ollamaId: "smollm2:360m",
  },

  // ╔══════════════════════════════════════════════════╗
  // ║  VISION / MULTIMODAL MODELS                      ║
  // ╚══════════════════════════════════════════════════╝
  {
    id: "llava-1.6-34b",
    name: "LLaVA 1.6 34B (NeXT)",
    family: "LLaVA",
    category: "vision",
    tags: ["vision", "multimodal", "image-understanding"],
    params: "34B",
    context: 4_096,
    vramGb: 21,
    quant: "Q4_K_M",
    tier: "medium",
    strengths: ["Strong image understanding", "Open architecture", "Apache 2.0"],
    weaknesses: ["4K text context", "No video"],
    license: "Apache 2.0",
    released: "2024-01",
    ollamaId: "llava:34b",
  },
  {
    id: "llava-1.6-13b",
    name: "LLaVA 1.6 13B",
    family: "LLaVA",
    category: "vision",
    tags: ["vision", "multimodal"],
    params: "13B",
    context: 4_096,
    vramGb: 8,
    quant: "Q4_K_M",
    tier: "light",
    strengths: ["Good vision at moderate size", "Apache 2.0"],
    weaknesses: ["4K context"],
    license: "Apache 2.0",
    released: "2024-01",
    ollamaId: "llava:13b",
  },
  {
    id: "llava-1.6-7b",
    name: "LLaVA 1.6 7B",
    family: "LLaVA",
    category: "vision",
    tags: ["vision", "multimodal", "lightweight"],
    params: "7B",
    context: 4_096,
    vramGb: 5,
    quant: "Q4_K_M",
    tier: "light",
    strengths: ["Lightweight vision model", "Apache 2.0"],
    weaknesses: ["4K context", "Basic vision quality"],
    license: "Apache 2.0",
    released: "2024-01",
    ollamaId: "llava:7b",
  },
  {
    id: "moondream-2-1.9b",
    name: "Moondream 2 1.9B",
    family: "Moondream",
    category: "vision",
    tags: ["vision", "lightweight", "edge"],
    params: "1.9B",
    context: 2_048,
    vramGb: 2,
    quant: "Q8_0",
    tier: "tiny",
    strengths: ["Tiny vision model", "Runs on edge", "Good OCR"],
    weaknesses: ["2K context", "Limited reasoning"],
    license: "Apache 2.0",
    released: "2024-03",
    ollamaId: "moondream:1.8b",
  },
  {
    id: "minicpm-v-2.6-8b",
    name: "MiniCPM-V 2.6 8B",
    family: "MiniCPM",
    category: "vision",
    tags: ["vision", "multimodal", "video", "OCR"],
    params: "8B",
    context: 32_768,
    vramGb: 6,
    quant: "Q4_K_M",
    tier: "light",
    strengths: ["Real-time video understanding", "Multi-image", "Strong OCR"],
    weaknesses: ["Apache 2.0 but with CPML restrictions"],
    license: "Apache 2.0",
    released: "2024-08",
    ollamaId: "minicpm-v",
  },
  {
    id: "internvl2-26b",
    name: "InternVL2 26B",
    family: "InternVL",
    category: "vision",
    tags: ["vision", "multimodal", "document", "chart"],
    params: "26B",
    context: 32_768,
    vramGb: 16,
    quant: "Q4_K_M",
    tier: "medium",
    strengths: ["Top-tier open vision model", "Document understanding", "Chart analysis"],
    weaknesses: ["Heavy for a vision model"],
    license: "MIT",
    released: "2024-07",
    ollamaId: "internvl2:26b",
  },
  {
    id: "bakllava-7b",
    name: "BakLLaVA 7B",
    family: "LLaVA",
    category: "vision",
    tags: ["vision", "multimodal", "lightweight"],
    params: "7B",
    context: 4_096,
    vramGb: 5,
    quant: "Q4_K_M",
    tier: "light",
    strengths: ["Mistral-based vision model", "Fast inference"],
    weaknesses: ["4K context", "Older"],
    license: "Apache 2.0",
    released: "2023-11",
    ollamaId: "bakllava:7b",
  },

  // ╔══════════════════════════════════════════════════╗
  // ║  EMBEDDING MODELS                                ║
  // ╚══════════════════════════════════════════════════╝
  {
    id: "nomic-embed-text",
    name: "Nomic Embed Text v1.5",
    family: "Nomic",
    category: "embedding",
    tags: ["embedding", "retrieval", "RAG", "search"],
    params: "137M",
    context: 8_192,
    vramGb: 0.3,
    quant: "FP16",
    tier: "tiny",
    strengths: ["Best lightweight embeddings", "8K context", "Apache 2.0", "Matryoshka representations"],
    weaknesses: ["Not as good as larger models"],
    license: "Apache 2.0",
    released: "2024-02",
    ollamaId: "nomic-embed-text",
    recommended: true,
  },
  {
    id: "mxbai-embed-large",
    name: "mxbai-embed-large",
    family: "Mixedbread",
    category: "embedding",
    tags: ["embedding", "retrieval", "RAG"],
    params: "335M",
    context: 512,
    vramGb: 0.7,
    quant: "FP16",
    tier: "tiny",
    strengths: ["Top-tier MTEB benchmark", "Apache 2.0"],
    weaknesses: ["512 token limit"],
    license: "Apache 2.0",
    released: "2024-03",
    ollamaId: "mxbai-embed-large",
  },
  {
    id: "bge-large-en-v1.5",
    name: "BGE Large English v1.5",
    family: "BGE",
    category: "embedding",
    tags: ["embedding", "retrieval", "RAG", "search"],
    params: "335M",
    context: 512,
    vramGb: 0.7,
    quant: "FP16",
    tier: "tiny",
    strengths: ["Strong English embeddings", "MIT license", "BAAI research"],
    weaknesses: ["512 token limit", "English only"],
    license: "MIT",
    released: "2023-09",
    ollamaId: "bge-large",
  },
  {
    id: "bge-m3",
    name: "BGE-M3",
    family: "BGE",
    category: "embedding",
    tags: ["embedding", "multilingual", "retrieval", "RAG"],
    params: "568M",
    context: 8_192,
    vramGb: 1.2,
    quant: "FP16",
    tier: "tiny",
    strengths: ["100+ languages", "8K context", "Dense + sparse + ColBERT", "MIT license"],
    weaknesses: ["Slightly larger than alternatives"],
    license: "MIT",
    released: "2024-01",
    ollamaId: "bge-m3",
    recommended: true,
  },
  {
    id: "all-minilm-l6-v2",
    name: "all-MiniLM-L6-v2",
    family: "Sentence-Transformers",
    category: "embedding",
    tags: ["embedding", "lightweight", "fast"],
    params: "22M",
    context: 256,
    vramGb: 0.1,
    quant: "FP32",
    tier: "tiny",
    strengths: ["Ultra-fast", "Tiny footprint", "Apache 2.0", "Great for prototyping"],
    weaknesses: ["256 token limit", "Lower quality"],
    license: "Apache 2.0",
    released: "2021-08",
    ollamaId: "all-minilm",
  },
  {
    id: "gte-large",
    name: "GTE-Large",
    family: "GTE",
    category: "embedding",
    tags: ["embedding", "retrieval", "Alibaba"],
    params: "335M",
    context: 8_192,
    vramGb: 0.7,
    quant: "FP16",
    tier: "tiny",
    strengths: ["8K context", "Strong MTEB performance", "MIT license"],
    weaknesses: ["English focused"],
    license: "MIT",
    released: "2024-06",
    ollamaId: "gte-large",
  },
  {
    id: "snowflake-arctic-embed-l",
    name: "Snowflake Arctic Embed L",
    family: "Arctic",
    category: "embedding",
    tags: ["embedding", "retrieval", "enterprise"],
    params: "335M",
    context: 512,
    vramGb: 0.7,
    quant: "FP16",
    tier: "tiny",
    strengths: ["#1 MTEB retrieval benchmark", "Apache 2.0"],
    weaknesses: ["512 token limit"],
    license: "Apache 2.0",
    released: "2024-04",
    ollamaId: "snowflake-arctic-embed:335m",
  },
  {
    id: "e5-mistral-7b",
    name: "E5 Mistral 7B Instruct",
    family: "E5",
    category: "embedding",
    tags: ["embedding", "retrieval", "instruction-based"],
    params: "7B",
    context: 32_768,
    vramGb: 5,
    quant: "Q4_K_M",
    tier: "light",
    strengths: ["32K context embeddings", "Instruction-tuned", "Top retrieval quality"],
    weaknesses: ["Heavy for an embedding model"],
    license: "MIT",
    released: "2024-01",
    ollamaId: "e5-mistral",
  },
  {
    id: "jina-embeddings-v3",
    name: "Jina Embeddings v3",
    family: "Jina",
    category: "embedding",
    tags: ["embedding", "multilingual", "8K-context"],
    params: "572M",
    context: 8_192,
    vramGb: 1.2,
    quant: "FP16",
    tier: "tiny",
    strengths: ["89 languages", "8K context", "Task-specific LoRA adapters"],
    weaknesses: ["CC-BY-NC license"],
    license: "CC-BY-NC-4.0",
    released: "2024-09",
    ollamaId: "jina-embeddings-v3",
  },

  // ╔══════════════════════════════════════════════════╗
  // ║  IMAGE GENERATION                                ║
  // ╚══════════════════════════════════════════════════╝
  {
    id: "stable-diffusion-xl",
    name: "Stable Diffusion XL 1.0",
    family: "Stable Diffusion",
    category: "image",
    tags: ["image-generation", "text-to-image", "1024px"],
    params: "6.6B",
    context: 77,
    vramGb: 8,
    quant: "FP16",
    tier: "light",
    strengths: ["1024×1024 generation", "Huge community", "LoRA ecosystem", "Stable-AI open model"],
    weaknesses: ["Superseded by FLUX and SD3", "StabilityAI license"],
    license: "Stability AI Open",
    released: "2023-07",
    ollamaId: undefined,
    huggingFaceId: "stabilityai/stable-diffusion-xl-base-1.0",
    recommended: true,
  },
  {
    id: "stable-diffusion-3-medium",
    name: "Stable Diffusion 3 Medium",
    family: "Stable Diffusion",
    category: "image",
    tags: ["image-generation", "text-to-image", "MMDiT"],
    params: "2B",
    context: 77,
    vramGb: 6,
    quant: "FP16",
    tier: "light",
    strengths: ["MMDiT architecture", "Better text rendering", "More coherent compositions"],
    weaknesses: ["Stability AI Community License", "Smaller LoRA community"],
    license: "Stability AI Community",
    released: "2024-06",
    ollamaId: undefined,
    huggingFaceId: "stabilityai/stable-diffusion-3-medium",
  },
  {
    id: "stable-diffusion-3.5-large",
    name: "Stable Diffusion 3.5 Large",
    family: "Stable Diffusion",
    category: "image",
    tags: ["image-generation", "text-to-image", "MMDiT"],
    params: "8B",
    context: 77,
    vramGb: 12,
    quant: "FP16",
    tier: "medium",
    strengths: ["Best SD yet", "QKV normalization", "Great at photorealism"],
    weaknesses: ["Needs 12GB+ VRAM"],
    license: "Stability AI Community",
    released: "2024-10",
    ollamaId: undefined,
    huggingFaceId: "stabilityai/stable-diffusion-3.5-large",
  },
  {
    id: "flux-1-schnell",
    name: "FLUX.1 Schnell",
    family: "FLUX",
    category: "image",
    tags: ["image-generation", "text-to-image", "fast"],
    params: "12B",
    context: 512,
    vramGb: 12,
    quant: "FP16",
    tier: "medium",
    strengths: ["4-step generation (fast!)", "Apache 2.0", "Best quality/speed tradeoff"],
    weaknesses: ["Needs 12GB+ VRAM"],
    license: "Apache 2.0",
    released: "2024-08",
    ollamaId: undefined,
    huggingFaceId: "black-forest-labs/FLUX.1-schnell",
    recommended: true,
  },
  {
    id: "flux-1-dev",
    name: "FLUX.1 Dev",
    family: "FLUX",
    category: "image",
    tags: ["image-generation", "text-to-image", "high-quality"],
    params: "12B",
    context: 512,
    vramGb: 16,
    quant: "FP16",
    tier: "medium",
    strengths: ["Top-tier image quality", "Great text rendering", "Distillable"],
    weaknesses: ["Needs 16GB+ VRAM", "Non-commercial license"],
    license: "FLUX.1-dev Non-Commercial",
    released: "2024-08",
    ollamaId: undefined,
    huggingFaceId: "black-forest-labs/FLUX.1-dev",
  },
  {
    id: "flux-1-pro",
    name: "FLUX.1 Pro",
    family: "FLUX",
    category: "image",
    tags: ["image-generation", "text-to-image", "flagship"],
    params: "12B",
    context: 512,
    vramGb: 24,
    quant: "FP16",
    tier: "medium",
    strengths: ["Best open image model", "Exceptional quality", "Great text in images"],
    weaknesses: ["API-only / commercial license"],
    license: "Commercial",
    released: "2024-08",
    ollamaId: undefined,
    huggingFaceId: "black-forest-labs/FLUX.1-pro",
  },

  // ╔══════════════════════════════════════════════════╗
  // ║  AUDIO / SPEECH MODELS                           ║
  // ╚══════════════════════════════════════════════════╝
  {
    id: "whisper-large-v3",
    name: "Whisper Large V3",
    family: "Whisper",
    category: "audio",
    tags: ["speech-to-text", "transcription", "translation", "99-languages"],
    params: "1.5B",
    context: 30,
    vramGb: 4,
    quant: "FP16",
    tier: "light",
    strengths: ["99 languages", "Near-human transcription", "Translation built-in", "Apache 2.0"],
    weaknesses: ["Batch only (not real-time streaming)", "30-sec chunks"],
    license: "Apache 2.0",
    released: "2023-11",
    ollamaId: undefined,
    huggingFaceId: "openai/whisper-large-v3",
    recommended: true,
  },
  {
    id: "whisper-large-v3-turbo",
    name: "Whisper Large V3 Turbo",
    family: "Whisper",
    category: "audio",
    tags: ["speech-to-text", "transcription", "fast"],
    params: "809M",
    context: 30,
    vramGb: 2,
    quant: "FP16",
    tier: "tiny",
    strengths: ["8x faster than V3", "Distilled quality", "Apache 2.0"],
    weaknesses: ["Slightly lower accuracy than V3"],
    license: "Apache 2.0",
    released: "2024-10",
    ollamaId: undefined,
    huggingFaceId: "openai/whisper-large-v3-turbo",
  },
  {
    id: "whisper-medium",
    name: "Whisper Medium",
    family: "Whisper",
    category: "audio",
    tags: ["speech-to-text", "lightweight"],
    params: "769M",
    context: 30,
    vramGb: 2,
    quant: "FP16",
    tier: "tiny",
    strengths: ["Good quality/speed balance", "99 languages"],
    weaknesses: ["Lower accuracy than Large V3"],
    license: "Apache 2.0",
    released: "2022-09",
    ollamaId: undefined,
    huggingFaceId: "openai/whisper-medium",
  },
  {
    id: "whisper-small",
    name: "Whisper Small",
    family: "Whisper",
    category: "audio",
    tags: ["speech-to-text", "edge", "lightweight"],
    params: "244M",
    context: 30,
    vramGb: 1,
    quant: "FP16",
    tier: "tiny",
    strengths: ["Fast edge transcription", "99 languages"],
    weaknesses: ["Lower accuracy"],
    license: "Apache 2.0",
    released: "2022-09",
    ollamaId: undefined,
    huggingFaceId: "openai/whisper-small",
  },
  {
    id: "bark",
    name: "Bark (Suno AI)",
    family: "Bark",
    category: "audio",
    tags: ["text-to-speech", "TTS", "multilingual", "music"],
    params: "1B",
    context: 256,
    vramGb: 4,
    quant: "FP16",
    tier: "light",
    strengths: ["Text-to-speech + music + effects", "Multilingual voices", "MIT license"],
    weaknesses: ["Slow generation", "Variable quality"],
    license: "MIT",
    released: "2023-04",
    ollamaId: undefined,
    huggingFaceId: "suno/bark",
  },
  {
    id: "parler-tts-large",
    name: "Parler TTS Large v1",
    family: "Parler",
    category: "audio",
    tags: ["text-to-speech", "TTS", "controllable"],
    params: "2.3B",
    context: 512,
    vramGb: 6,
    quant: "FP16",
    tier: "light",
    strengths: ["Describe voice with text prompt", "High quality TTS", "Apache 2.0"],
    weaknesses: ["English only", "Slower than XTTS"],
    license: "Apache 2.0",
    released: "2024-08",
    ollamaId: undefined,
    huggingFaceId: "parler-tts/parler-tts-large-v1",
  },
  {
    id: "xtts-v2",
    name: "XTTS v2 (Coqui)",
    family: "XTTS",
    category: "audio",
    tags: ["text-to-speech", "TTS", "voice-cloning", "multilingual"],
    params: "467M",
    context: 400,
    vramGb: 2,
    quant: "FP32",
    tier: "tiny",
    strengths: ["Voice cloning from 6-sec sample", "17 languages", "Real-time streaming"],
    weaknesses: ["Coqui Public Model License (non-commercial)"],
    license: "CPML",
    released: "2023-11",
    ollamaId: undefined,
    huggingFaceId: "coqui/XTTS-v2",
  },

  // ╔══════════════════════════════════════════════════╗
  // ║  CLASSIFIER / NLP MODELS                         ║
  // ╚══════════════════════════════════════════════════╝
  {
    id: "deberta-v3-large-nli",
    name: "DeBERTa V3 Large (NLI)",
    family: "DeBERTa",
    category: "classifier",
    tags: ["classifier", "NLI", "zero-shot", "sentiment"],
    params: "435M",
    context: 512,
    vramGb: 1,
    quant: "FP16",
    tier: "tiny",
    strengths: ["Zero-shot classification", "State-of-art NLI", "MIT license"],
    weaknesses: ["Not generative", "512 token limit"],
    license: "MIT",
    released: "2023-01",
    ollamaId: undefined,
    vllmId: "cross-encoder/nli-deberta-v3-large",
    huggingFaceId: "cross-encoder/nli-deberta-v3-large",
  },
  {
    id: "modernbert-large",
    name: "ModernBERT Large",
    family: "ModernBERT",
    category: "classifier",
    tags: ["classifier", "NER", "token-classification", "retrieval"],
    params: "396M",
    context: 8_192,
    vramGb: 0.8,
    quant: "FP16",
    tier: "tiny",
    strengths: ["8K context (vs 512 for BERT)", "Flash Attention 2", "Apache 2.0", "Drop-in BERT replacement"],
    weaknesses: ["Not generative"],
    license: "Apache 2.0",
    vllmId: "answerdotai/ModernBERT-large",
    huggingFaceId: "answerdotai/ModernBERT-large",
    released: "2024-12",
    ollamaId: undefined,
    recommended: true,
  },
  {
    id: "roberta-large-mnli",
    name: "RoBERTa Large (MNLI)",
    family: "RoBERTa",
    category: "classifier",
    tags: ["classifier", "NLI", "zero-shot", "sentiment"],
    params: "355M",
    context: 512,
    vramGb: 0.7,
    quant: "FP16",
    tier: "tiny",
    strengths: ["Proven zero-shot classification", "MIT license"],
    weaknesses: ["512 token limit", "Older architecture"],
    license: "MIT",
    released: "2019-07",
    ollamaId: undefined,
    vllmId: "FacebookAI/roberta-large-mnli",
    huggingFaceId: "FacebookAI/roberta-large-mnli",
  },
  {
    id: "bert-base-uncased",
    name: "BERT Base Uncased",
    family: "BERT",
    category: "classifier",
    tags: ["classifier", "NER", "QA", "token-classification"],
    params: "110M",
    context: 512,
    vramGb: 0.3,
    quant: "FP32",
    tier: "tiny",
    strengths: ["Pioneer model — universal fine-tuning base", "Apache 2.0", "Massive ecosystem"],
    weaknesses: ["512 token limit", "Superseded by ModernBERT"],
    license: "Apache 2.0",
    released: "2018-10",
    ollamaId: undefined,
    vllmId: "google-bert/bert-base-uncased",
    huggingFaceId: "google-bert/bert-base-uncased",
  },
  {
    id: "distilbert-base",
    name: "DistilBERT Base",
    family: "DistilBERT",
    category: "classifier",
    tags: ["classifier", "lightweight", "fast", "sentiment"],
    params: "66M",
    context: 512,
    vramGb: 0.2,
    quant: "FP32",
    tier: "tiny",
    strengths: ["60% faster than BERT", "97% of BERT accuracy", "Apache 2.0"],
    weaknesses: ["512 token limit"],
    license: "Apache 2.0",
    released: "2019-08",
    ollamaId: undefined,
    vllmId: "distilbert/distilbert-base-uncased",
    huggingFaceId: "distilbert/distilbert-base-uncased",
  },
  {
    id: "xlm-roberta-large",
    name: "XLM-RoBERTa Large",
    family: "XLM-R",
    category: "classifier",
    tags: ["classifier", "multilingual", "100-languages", "NER"],
    params: "560M",
    context: 512,
    vramGb: 1.2,
    quant: "FP16",
    tier: "tiny",
    strengths: ["100 languages", "Strong cross-lingual transfer", "MIT license"],
    weaknesses: ["512 token limit"],
    license: "MIT",
    released: "2019-11",
    ollamaId: undefined,
    vllmId: "FacebookAI/xlm-roberta-large",
    huggingFaceId: "FacebookAI/xlm-roberta-large",
  },

  // ╔══════════════════════════════════════════════════╗
  // ║  MISC / SPECIALIZED                              ║
  // ╚══════════════════════════════════════════════════╝
  {
    id: "rwkv-6-world-7b",
    name: "RWKV-6 World 7B",
    family: "RWKV",
    category: "chat",
    tags: ["chat", "RNN", "linear-attention", "infinite-context"],
    params: "7B",
    context: 0, // effectively unlimited
    vramGb: 5,
    quant: "Q4_K_M",
    tier: "light",
    strengths: ["RNN — O(1) memory per token", "Theoretically infinite context", "Apache 2.0"],
    weaknesses: ["Lower peak quality vs transformers", "Smaller community"],
    license: "Apache 2.0",
    released: "2024-06",
    ollamaId: "rwkv-6",
  },
  {
    id: "mamba-2-2.8b",
    name: "Mamba 2 2.8B",
    family: "Mamba",
    category: "chat",
    tags: ["chat", "state-space", "linear-time", "edge"],
    params: "2.8B",
    context: 0, // unlimited
    vramGb: 2,
    quant: "FP16",
    tier: "tiny",
    strengths: ["State-space model — O(1) inference", "Very fast generation", "Apache 2.0"],
    weaknesses: ["Lower quality than transformers at same size"],
    license: "Apache 2.0",
    released: "2024-05",
    ollamaId: undefined,
    vllmId: "state-spaces/mamba-2.8b",
    huggingFaceId: "state-spaces/mamba-2.8b",
  },
  {
    id: "tinyllama-1.1b",
    name: "TinyLlama 1.1B Chat",
    family: "TinyLlama",
    category: "chat",
    tags: ["chat", "lightweight", "edge", "mobile"],
    params: "1.1B",
    context: 2_048,
    vramGb: 1,
    quant: "Q8_0",
    tier: "tiny",
    strengths: ["Ultra-tiny", "Runs on anything", "Apache 2.0"],
    weaknesses: ["2K context", "Very limited quality"],
    license: "Apache 2.0",
    released: "2024-01",
    ollamaId: "tinyllama:1.1b",
  },
  {
    id: "dolphin-2.9-llama3.1-8b",
    name: "Dolphin 2.9.4 Llama 3.1 8B",
    family: "Dolphin",
    category: "chat",
    tags: ["chat", "uncensored", "instruction-following"],
    params: "8B",
    context: 128_000,
    vramGb: 5,
    quant: "Q4_K_M",
    tier: "light",
    strengths: ["Uncensored model", "128K context", "Strong instruction following"],
    weaknesses: ["No safety guardrails"],
    license: "Llama 3.1 Community",
    released: "2024-08",
    ollamaId: "dolphin-llama3:8b",
  },
  {
    id: "nous-hermes-2-mixtral-8x7b",
    name: "Nous Hermes 2 Mixtral 8x7B",
    family: "Nous",
    category: "chat",
    tags: ["chat", "MoE", "function-calling", "tool-use"],
    params: "8x7B",
    context: 32_768,
    vramGb: 26,
    quant: "Q4_K_M",
    tier: "medium",
    strengths: ["Function calling", "JSON mode", "Strong instruction following"],
    weaknesses: ["32K context", "Heavy footprint"],
    license: "Apache 2.0",
    released: "2024-01",
    ollamaId: "nous-hermes2-mixtral",
  },
  {
    id: "wizardlm-2-8x22b",
    name: "WizardLM-2 8x22B",
    family: "WizardLM",
    category: "chat",
    tags: ["chat", "MoE", "reasoning"],
    params: "8x22B",
    context: 65_536,
    vramGb: 80,
    quant: "Q4_K_M",
    tier: "ultra",
    strengths: ["Strong reasoning", "64K context"],
    weaknesses: ["Extremely heavy", "Non-commercial"],
    license: "Microsoft Research",
    released: "2024-04",
    ollamaId: "wizardlm2:8x22b",
  },
  {
    id: "meditron-70b",
    name: "Meditron 70B",
    family: "Meditron",
    category: "chat",
    tags: ["chat", "medical", "clinical", "healthcare"],
    params: "70B",
    context: 4_096,
    vramGb: 40,
    quant: "Q4_K_M",
    tier: "heavy",
    strengths: ["Medical domain specialist", "Clinical guidelines trained", "Llama 2 base"],
    weaknesses: ["4K context", "Not for diagnosis use"],
    license: "Llama 2 Community",
    released: "2023-11",
    ollamaId: "meditron:70b",
  },
  {
    id: "sqlcoder-34b",
    name: "SQLCoder 34B",
    family: "SQLCoder",
    category: "code",
    tags: ["code", "SQL", "text-to-SQL", "database"],
    params: "34B",
    context: 16_384,
    vramGb: 21,
    quant: "Q4_K_M",
    tier: "medium",
    strengths: ["Beats GPT-4 at text-to-SQL", "Natural language to SQL", "Apache 2.0"],
    weaknesses: ["SQL only — not general purpose"],
    license: "Apache 2.0",
    released: "2024-01",
    ollamaId: "sqlcoder:34b",
  },
  {
    id: "sqlcoder-7b",
    name: "SQLCoder 7B",
    family: "SQLCoder",
    category: "code",
    tags: ["code", "SQL", "text-to-SQL", "lightweight"],
    params: "7B",
    context: 16_384,
    vramGb: 5,
    quant: "Q4_K_M",
    tier: "light",
    strengths: ["Good text-to-SQL at 7B", "Apache 2.0"],
    weaknesses: ["Less accurate than 34B"],
    license: "Apache 2.0",
    released: "2023-10",
    ollamaId: "sqlcoder:7b",
  },
];

// ── Helpers ──────────────────────────────────────────

/** All distinct categories present in the catalog */
export const MODEL_CATEGORIES: { id: ModelCategory; label: string }[] = [
  { id: "chat", label: "Chat / General" },
  { id: "reasoning", label: "Reasoning / Math" },
  { id: "code", label: "Code Generation" },
  { id: "vision", label: "Vision / Multimodal" },
  { id: "image", label: "Image Generation" },
  { id: "embedding", label: "Embeddings / RAG" },
  { id: "audio", label: "Audio / Speech" },
  { id: "classifier", label: "Classifiers / NLP" },
  { id: "multimodal", label: "Multimodal" },
];

/** All distinct families for grouping */
export function getModelFamilies(): string[] {
  const families = new Set(MODEL_CATALOG.map((m) => m.family));
  return [...families].sort();
}

/** Filter catalog by category, tier, and search text */
export function filterModels(opts: {
  category?: ModelCategory | "all";
  tier?: HardwareTier | "all";
  search?: string;
  recommendedOnly?: boolean;
  /** If true, include models without any local backend. Default: false (only show usable models). */
  includeNonLocal?: boolean;
}): ModelEntry[] {
  let results = MODEL_CATALOG;

  // Show all models with at least one backend (Ollama, vLLM, or HuggingFace link)
  if (!opts.includeNonLocal) {
    results = results.filter((m) => !!m.ollamaId || !!m.vllmId || !!m.huggingFaceId);
  }

  if (opts.category && opts.category !== "all") {
    results = results.filter((m) => m.category === opts.category || m.tags.includes(opts.category!));
  }

  if (opts.tier && opts.tier !== "all") {
    const tierOrder: HardwareTier[] = ["tiny", "light", "medium", "heavy", "ultra"];
    const maxIdx = tierOrder.indexOf(opts.tier);
    results = results.filter((m) => tierOrder.indexOf(m.tier) <= maxIdx);
  }

  if (opts.recommendedOnly) {
    results = results.filter((m) => m.recommended);
  }

  if (opts.search) {
    const q = opts.search.toLowerCase();
    results = results.filter(
      (m) =>
        m.name.toLowerCase().includes(q) ||
        m.family.toLowerCase().includes(q) ||
        m.id.toLowerCase().includes(q) ||
        m.tags.some((t) => t.includes(q)),
    );
  }

  return results;
}

/** Hardware tier label + description */
export const HARDWARE_TIERS: { id: HardwareTier; label: string; desc: string; vram: string }[] = [
  { id: "tiny", label: "Tiny", desc: "CPU / phone / RPi", vram: "0-4 GB" },
  { id: "light", label: "Light", desc: "Laptop GPU / iGPU", vram: "4-8 GB" },
  { id: "medium", label: "Medium", desc: "RTX 3090/4090 / M2 Pro", vram: "12-24 GB" },
  { id: "heavy", label: "Heavy", desc: "A6000 / M2 Ultra / 2x 4090", vram: "48-80 GB" },
  { id: "ultra", label: "Ultra", desc: "A100 / H100 cluster", vram: "80+ GB" },
];

/** Total count */
export const MODEL_COUNT = MODEL_CATALOG.length;
