{{- if and .Values.bridge.enabled .Values.bridge.internalSecret (not .Values.bridge.internalSecretExistingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pilox-transport-bridge.fullname" . }}-bridge-internal
  labels:
    {{- include "pilox-transport-bridge.labels" . | nindent 4 }}
type: Opaque
stringData:
  BRIDGE_INTERNAL_SECRET: {{ .Values.bridge.internalSecret | quote }}
{{- end }}
